# Generated by Django 4.2.23 on 2025-10-23 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_prodi_akreditasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultas',
            name='kodefakultas',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
