# Generated by Django 4.2.23 on 2025-10-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_matakuliah_angkatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='angkatan',
            field=models.CharField(max_length=10),
        ),
    ]
