# Generated by Django 4.2.23 on 2025-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_matakuliah_angkatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='courser',
            field=models.CharField(default='', max_length=150),
        ),
    ]
