# Generated by Django 4.2.23 on 2025-10-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_matakuliah_courser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='courser',
            field=models.CharField(max_length=150),
        ),
    ]
