# Generated by Django 4.2.23 on 2025-10-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_matakuliah_courser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matakuliah',
            old_name='courser',
            new_name='course',
        ),
    ]
