# Generated by Django 4.2.23 on 2025-10-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_courser_matakuliah_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='tglwisuda_en',
        ),
        migrations.RemoveField(
            model_name='mahasiswa',
            name='tglyudisium_en',
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='judul',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='noijazah',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='notranskip',
            field=models.CharField(default='', max_length=25),
        ),
    ]
