# Generated by Django 4.2.23 on 2025-10-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_mahasiswa_tglwisuda_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='noijazah',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='notranskip',
            field=models.CharField(max_length=25),
        ),
    ]
