# Generated by Django 4.2.23 on 2025-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mahasiswa_judul_alter_mahasiswa_noijazah_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakultas',
            name='akrelembaga',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='fakultas',
            name='pimpinanpt',
            field=models.CharField(default='', max_length=100),
        ),
    ]
