# Generated by Django 4.2.23 on 2025-10-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_fakultas_akrelembaga_fakultas_pimpinanpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakultas',
            name='akrelembaga',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fakultas',
            name='pimpinanpt',
            field=models.CharField(max_length=100),
        ),
    ]
