# Generated by Django 4.2.23 on 2025-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_fakultas_akrelembaga_alter_fakultas_pimpinanpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='semester',
            field=models.CharField(default='', max_length=10),
        ),
    ]
